### ISSUE TITLE
Deploy to crates.io for supporting cargo install

### ISSUE THREAD

**Issue by TheRustyPickle** [Jo6a/multitimer-tui#1]
Hello there! I hope you're doing well. I came across your repository and was exploring it. I noticed that the project hasn't been deployed on crates.io yet. If you're open to contributions, I'd be happy to do a pr and add the necessary components to make it compatible and ready for publishing. Please let me know your thoughts on this. Thank you!

**Comment by Jo6a** [comment]
Hello, thank you for the offer, I am happy to accept and look forward to your PR. Thank you!

**Comment by TheRustyPickle** [comment]
#2 resolves this
