### ISSUE TITLE
Add color coding for timers based on categories or priorities

### ISSUE THREAD

**Issue by Jo6a** [Jo6a/multitimer-tui#10]
It would be helpful to have a feature that allows the user to assign different colors to timers based on categories or priorities. For example, the user could have red timers for urgent tasks, green timers for important tasks, blue timers for optional tasks, etc. This would make it easier to organize and prioritize the timers. 

The feature could be implemented by adding a command like `color [id] [color]`, where id is the timer id and color is the color name.

**Comment by TheRustyPickle** [comment]
Hello, @Jo6a, how are you doing? I would like to work on this if it's alright. Also, what do you think of adding the color option directly available via the add commands? So the command would support something like this: `add [time] [color(optional)] [description]`

Another possibility would be giving the user a pre-set of configs like Urgent, Important, etc available where different colors can be set. In this case, the way to add color via add command would be `add [time] [type(optional)] [description]`

Just sharing some ideas! Let me know what you think of them.

**Comment by Jo6a** [comment]
Hi @TheRustyPickle, great suggestions, I think both are good. Your second suggestion of giving timers types like "urgent", "important", makes the most sense to me and would be very intuitive for first time users.

I am glad you are having so much fun implementing and fixing things in this project 😊
