### ISSUE TITLE
Port tui to ratatui

### ISSUE THREAD

**Issue by Jo6a** [Jo6a/multitimer-tui#11]
The tui crate is a text-based user interface library for Rust, but it is no longer actively maintained. The ratatui crate is a fork of tui that adds new features and fixes bugs. It would be beneficial to port our multitimer application to ratatui, as it would allow us to use the latest features and improvements of the library.

**Comment by TheRustyPickle** [comment]
Hello @Jo6a. hope you are well. Thanks for creating the issues, makes it easier for me to understand what you need help with. If you are alright with it, I can help tackle this issue. Let me know what you think.

**Comment by Jo6a** [comment]
Hello @TheRustyPickle! Yes, that would be great if you could tackle the issue. I created the issues just to help people like you. But don't feel obliged to do them all 😊
