### ISSUE TITLE
Proposal: give a fixed length to each added timer 

### ISSUE THREAD

**Issue by TheRustyPickle** [Jo6a/multitimer-tui#15]
**Current status:**
- Currently on the timer tab the space for each timer is decided based on `90 / amount of timer`. Each timer requires 1 line of room for the text and the rest remains empty. 
- If there is not enough space on the terminal, almost nothing gets shown
- Some timers may have uneven space between others. Refer to pic below

![Screenshot from 2023-07-16 05-12-04](https://github.com/Jo6a/multitimer-tui/assets/35862475/7e9be132-1b9a-4039-854c-50b0ad65fc16)

**Proposed status:**
- Give each timer a fixed length based on the need
- Due to fixed size, regardless of the terminal space, shows all the timers that can be fit instead of lowering room for other timers
- Empty room between timer remains even. Refer to pic below

![Screenshot from 2023-07-16 05-10-20](https://github.com/Jo6a/multitimer-tui/assets/35862475/7c3cdf75-e41e-498a-85d3-2d62b7a3a067)

@Jo6a let me know what you think of it. To give you more context, I was trying to add a progress bar but due to the uneven length of each timer, it didn't look very nice to me. I would love to hear your thoughts!

**Comment by Jo6a** [comment]
Hi @TheRustyPickle, nice to hear from you. 

Yes, I was thinking about the same thing, and I also think it is better to give each timer a fixed length based on need. 
I totally agree, even in the current version it's annoying when you can't see anything because you have too many timers. 

So a great issue that I can only support.

**Comment by TheRustyPickle** [comment]
@Jo6a Currently experimenting with the borders a bit. Can you let me know which one you prefer so I can share a pr?

**1. Current style** 
![Screenshot from 2023-07-17 00-19-42](https://github.com/Jo6a/multitimer-tui/assets/35862475/cfc17f8a-1857-445d-bafa-c0bc1371d7bf)

**2. Another style**
![Screenshot from 2023-07-17 00-08-08](https://github.com/Jo6a/multitimer-tui/assets/35862475/c6870850-486d-4ba6-a0c0-8a3119c0dd04)

**Comment by Jo6a** [comment]
Very cool, I like both, but in the current state I would prefer the first one, which looks very clean. With the second suggestion, the timer boxes look cool, but you have these empty boxes with frames underneath that look a bit out of place. The second suggestion would be nicer if the frames under the timers were gone. What do you think?

**Comment by TheRustyPickle** [comment]
@Jo6a Did you have something like this in mind?

![Screenshot from 2023-07-17 02-17-03](https://github.com/Jo6a/multitimer-tui/assets/35862475/c58714dc-41ff-4ee2-8ac7-455ae365db30)

**Comment by Jo6a** [comment]
Yes, this is exactly what was in my mind. This is my favourite out of the three. Nice work! Feel free to share the pr 😊

**Comment by TheRustyPickle** [comment]
Resolved on #17
