### ISSUE TITLE
Unused dependencies

### ISSUE THREAD

**Issue by TheRustyPickle** [Jo6a/multitimer-tui#19]
I noticed a few used dependencies on `cargo.toml` file. They are the following
- bitflags
- cassowary
- unicode-segmentation
- unicode-width
- termion
- rand

Are they for some upcoming feature or do they have any purpose? If not, they should be removed. The app compiles without them as dependencies.

**Comment by Jo6a** [comment]
Good hint, the dependencies are not intentional.

**Comment by TheRustyPickle** [comment]
Thanks for letting me know. If it's alright, I'll share a PR and remove the unused dependencies.
