### ISSUE TITLE
Loading bar broke the functionality of the plus command

### ISSUE THREAD

**Issue by Jo6a** [Jo6a/multitimer-tui#20]
@TheRustyPickle Unfortunately, the loading bar broke the functionality of the `plus` command.

If I have a timer `@0` and execute the command `plus 0 10`, the following error occurs:

thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.', C:\Users\..\.cargo\registry\src\github.com-1ecc6299db9ec823\ratatui-0.21.0\src\widgets\gauge.rs:62:9

**Comment by TheRustyPickle** [comment]
@Jo6a I'll share a fix asap. Thanks for the heads up.
