### ISSUE TITLE
Modify config using left/right arrow

### ISSUE THREAD

**Issue by TheRustyPickle** [Jo6a/multitimer-tui#4]
Hello, @Jo6a! Hope you are doing well. I noticed on the config page to switch darkmode for example have to type true/false manually. What do you think of allowing to change the values with left/right arrow keys in the config page instead of typing manually? Let me know your thoughts on it. Thank you!

**Comment by Jo6a** [comment]
Hi @TheRustyPickle. I'm pleased to hear from you. Yes, switching would be even easier with the arrow keys, I think that's good. Thank you!

**Comment by TheRustyPickle** [comment]
Awesome! I'll be working on this then and send a PR once I'm done.
