### ISSUE TITLE
Display the remaining time or percentage of each timer in a graphical way

### ISSUE THREAD

**Issue by Jo6a** [Jo6a/multitimer-tui#8]
It would be nice to have an option to display the remaining time or percentage of each timer in a graphical way, such as a progress bar. This would make it easier to see how much time is left for each timer and how far along they are.

**Comment by TheRustyPickle** [comment]
Hello @Jo6a, hope you are doing well! What do you think of this to show the percentage?

![Screenshot from 2023-07-18 01-53-20](https://github.com/Jo6a/multitimer-tui/assets/35862475/1c20b99a-ddd4-4e5f-9a7d-6058eae1c95c)

**Comment by Jo6a** [comment]
Hi @TheRustyPickle, that's how I imagined it! 
Only I see myself in situations where I have a lot of timers, where it would be good to turn off the feature to have more space. So if you could make it configurable in the Config tab, it would be ideal. 

Good job and thank you for the great support!

**Comment by TheRustyPickle** [comment]
How about showing the percentage bar only of the active timers and the rest will only show the text?

**Comment by Jo6a** [comment]
Yes, I think it's great, then not much space is taken up and it looks clean. Very good suggestion!
